import type { Patient } from './types';

export const patients: Patient[] = [
  {
    id: 1, name: 'Patient 1 — Diabetic ACS', age: 65, sex: 'M', isDemo: true,
    medications: [
      { name: 'Metformin', dose: '1g BD' },
      { name: 'Glimepiride', dose: '2mg OD' },
      { name: 'Telmisartan', dose: '40mg OD' },
      { name: 'Atorvastatin', dose: '20mg HS' },
    ],
    allergies: [{ allergen: 'Penicillin', reaction: 'ANAPHYLAXIS', severity: 'anaphylaxis' }],
    labs: { creatinine: 2.1, eGFR: 31.2, hba1c: 8.4, potassium: 5.1, troponin: 4.8 },
    vitals: { hr: 110, bp_systolic: 90, bp_diastolic: 60, spo2: 94 },
    notes: 'Demo Scenario 2: Penicillin anaphylaxis + CKD',
  },
  {
    id: 2, name: 'Patient 2 — Post-op Pain', age: 58, sex: 'F', isDemo: false,
    medications: [
      { name: 'Enoxaparin', dose: '40mg SC' },
      { name: 'Paracetamol', dose: '1g QDS' },
      { name: 'Tramadol', dose: '50mg TDS' },
      { name: 'Pantoprazole', dose: '40mg' },
    ],
    allergies: [{ allergen: 'NKDA', reaction: 'None', severity: 'mild' }],
    labs: { creatinine: 0.9, eGFR: 82, hemoglobin: 10.2 },
  },
  {
    id: 3, name: 'Patient 3 — Polypharmacy Elderly', age: 78, sex: 'M', isDemo: true,
    medications: [
      { name: 'Amlodipine', dose: '10mg' },
      { name: 'Telmisartan', dose: '80mg' },
      { name: 'Metformin', dose: '500mg BD' },
      { name: 'Glimepiride', dose: '1mg' },
      { name: 'Atorvastatin', dose: '40mg' },
      { name: 'Aspirin', dose: '75mg' },
      { name: 'Pantoprazole', dose: '20mg' },
      { name: 'Escitalopram', dose: '10mg' },
      { name: 'Tamsulosin', dose: '0.4mg' },
      { name: 'Paracetamol', dose: 'PRN' },
      { name: 'Diclofenac', dose: 'PRN (OTC)' },
      { name: 'Calcium+D3', dose: 'daily' },
    ],
    allergies: [{ allergen: 'Sulfonamide', reaction: 'Rash', severity: 'mild' }],
    labs: { creatinine: 1.4, eGFR: 48, potassium: 4.8 },
    notes: 'Demo Scenario 1: Polypharmacy + Clarithromycin risk',
  },
  {
    id: 4, name: 'Patient 4 — Pediatric Epilepsy', age: 6, sex: 'M', weight: 20, isDemo: false,
    medications: [
      { name: 'Sodium Valproate', dose: '200mg BD' },
      { name: 'Levetiracetam', dose: '250mg BD' },
    ],
    allergies: [{ allergen: 'NKDA', reaction: 'None', severity: 'mild' }],
    labs: { valproateLevel: 85 },
  },
  {
    id: 5, name: 'Patient 5 — CKD Stage 5', age: 62, sex: 'M', isDemo: false,
    medications: [
      { name: 'Furosemide', dose: '80mg BD' },
      { name: 'Carvedilol', dose: '12.5mg BD' },
      { name: 'Amlodipine', dose: '5mg' },
      { name: 'Calcium', dose: '500mg TDS' },
    ],
    allergies: [{ allergen: 'ACE inhibitor', reaction: 'Angioedema', severity: 'severe' }],
    labs: { creatinine: 4.8, eGFR: 12, potassium: 5.6 },
    notes: 'CKD Stage 5. ACE inhibitor angioedema history.',
  },
  {
    id: 6, name: 'Patient 6 — Pregnant HTN', age: 28, sex: 'F', isDemo: false,
    medications: [
      { name: 'Methyldopa', dose: '250mg TDS' },
      { name: 'Folic acid', dose: '5mg' },
      { name: 'Iron', dose: '200mg' },
    ],
    allergies: [{ allergen: 'Codeine', reaction: 'Nausea', severity: 'mild' }],
    labs: { hemoglobin: 10.8, creatinine: 0.6 },
    notes: '32 weeks pregnant',
  },
  {
    id: 7, name: 'Patient 7 — ICU Sepsis', age: 35, sex: 'F', isDemo: true,
    medications: [
      { name: 'Meropenem', dose: '1g IV TDS' },
      { name: 'Enoxaparin', dose: '40mg' },
      { name: 'Pantoprazole', dose: '40mg IV' },
    ],
    allergies: [{ allergen: 'Penicillin', reaction: 'Rash (NOT anaphylaxis)', severity: 'mild' }],
    labs: { creatinine: 3.2, eGFR: 18, wbc: 22, lactate: 4.8 },
    vitals: { hr: 118, bp_systolic: 85, bp_diastolic: 50, spo2: 92, rr: 28, temp: 39.2 },
    notes: 'Demo Scenario 3: ICU, eGFR 18, Gabapentin dosing',
  },
  {
    id: 8, name: 'Patient 8 — AF + Heart Failure', age: 68, sex: 'M', isDemo: true,
    medications: [
      { name: 'Warfarin', dose: '5mg' },
      { name: 'Bisoprolol', dose: '5mg' },
      { name: 'Ramipril', dose: '5mg' },
      { name: 'Atorvastatin', dose: '80mg' },
      { name: 'Furosemide', dose: '40mg' },
      { name: 'Spironolactone', dose: '25mg' },
    ],
    allergies: [{ allergen: 'NKDA', reaction: 'None', severity: 'mild' }],
    labs: { creatinine: 1.1, eGFR: 62, potassium: 4.9, inr: 2.8, bnp: 450 },
    conditions: [
      { name: 'AF (Atrial Fibrillation)', active: true },
      { name: 'CHF (Heart Failure, EF 35%)', active: true },
      { name: 'HTN (Hypertension)', active: true },
      { name: 'T2DM (Diabetes)', active: true },
      { name: 'Previous TIA (2022)', active: true },
    ],
    notes: 'Demo Scenario 4: CHA2DS2-VASc calculation',
  },
  {
    id: 9, name: 'Patient 9 — Diabetic Neuropathy', age: 55, sex: 'M', isDemo: false,
    medications: [
      { name: 'Metformin', dose: '1g BD' },
      { name: 'Empagliflozin', dose: '10mg' },
      { name: 'Pregabalin', dose: '150mg BD' },
      { name: 'Duloxetine', dose: '60mg' },
      { name: 'Aspirin', dose: '75mg' },
    ],
    allergies: [{ allergen: 'Metoclopramide', reaction: 'Dystonia', severity: 'moderate' }],
    labs: { creatinine: 1.0, eGFR: 72, hba1c: 7.8 },
  },
  {
    id: 10, name: 'Patient 10 — Pediatric Asthma', age: 10, sex: 'F', weight: 35, isDemo: false,
    medications: [
      { name: 'Salbutamol', dose: 'PRN' },
      { name: 'Fluticasone', dose: '125μg BD' },
      { name: 'Montelukast', dose: '5mg' },
    ],
    allergies: [{ allergen: 'Aspirin', reaction: 'Bronchospasm', severity: 'severe' }],
    labs: { fev1: 78 },
    notes: 'Aspirin-exacerbated respiratory disease',
  },
];
